/*const LList = require('./linkedList')
var cities = new LList()
cities.insert('beijing', 'head')
cities.insert('shanghai', 'beijing')
cities.insert('xiamen', 'shanghai')
cities.insert('chengdu', 'xiamen')
cities.display()
cities.remove('xiamen')
cities.remove('chengdu')
cities.display()
console.log(cities.show())
cities.advance(2)
console.log(cities.show())*/

/*const DLList = require('./doubleLinkedList')
var evolutions = new DLList()
evolutions.insert('cell', 'head')
evolutions.insert('egg', 'cell')
evolutions.insert('chicken', 'egg')
evolutions.insert('roast-chicken', 'chicken')
evolutions.insert('goubi', 'egg')
evolutions.remove('goubi')
evolutions.display()
evolutions.displayReverse()
console.log(evolutions.show())
evolutions.advance(3)
console.log(evolutions.show())
evolutions.back(1)
console.log(evolutions.show())*/

const CLList = require('./circularLinkedList')
var circulars = new CLList()
circulars.insert(1)
circulars.insert(2)
circulars.insert(3)
circulars.insert(4)

circulars.remove(3)

circulars.display()
console.log(circulars.show())
circulars.advance(10)
console.log(circulars.show())